import { useEffect, useMemo, useState } from 'react';
import { FileText, Globe, Search, Send, RefreshCw } from 'lucide-react';
import { api } from '../services/api';

export default function ExportPage() {
  const [rows,setRows]=useState([]),[term,setTerm]=useState(''),[loading,setLoading]=useState(true),[busy,setBusy]=useState('');
  const load=async()=>{try{setLoading(true);const r=await api.export.ready();setRows(r.data||[])}catch(e){alert(e.message)}finally{setLoading(false)}};
  useEffect(()=>{load()},[]);
  const filtered=useMemo(()=>{const q=term.toUpperCase().trim();return rows.filter(r=>!q||[r.so,r.artikel,r.destination].some(v=>String(v||'').toUpperCase().includes(q)))},[rows,term]);
  const execute=async(so)=>{const row=rows.find(x=>x.so===so);if(!row||!confirm(`Export SO ${so}? This will move ${row.total_cartons} cartons / ${row.total_pcs} pcs to Export History.`))return;try{setBusy(so);await api.export.execute(so);await load();alert(`SO ${so} successfully exported.`)}catch(e){alert(e.message)}finally{setBusy('')}};
  return <div className="max-w-7xl mx-auto space-y-5"><div className="flex flex-col md:flex-row md:items-center md:justify-between gap-4"><div><h2 className="text-xl font-black">Export & Outbound</h2><p className="text-xs font-semibold text-textMuted mt-1">Outbound transaction is executed atomically by the backend.</p></div><div className="flex gap-2"><div className="relative w-full md:w-80"><Search size={15} className="absolute left-3.5 top-3 text-textMuted"/><input className="form-input pl-10 uppercase" placeholder="Search SO, Article, Destination..." value={term} onChange={e=>setTerm(e.target.value)}/></div><button onClick={load} className="px-3 rounded-xl border border-borderLight bg-surface"><RefreshCw size={16}/></button></div></div><div className="bg-surface border border-borderLight rounded-2xl shadow-sm overflow-hidden"><div className="overflow-x-auto"><table className="w-full min-w-[1000px]"><thead><tr className="bg-bgBody border-b border-borderLight text-[10px] uppercase text-textMuted"><th className="px-6 py-4 text-left">SO</th><th className="px-6 py-4 text-left">Article</th><th className="px-6 py-4 text-left">Destination</th><th className="px-6 py-4 text-center">Cartons</th><th className="px-6 py-4 text-center">Qty</th><th className="px-6 py-4 text-right">Action</th></tr></thead><tbody className="divide-y divide-borderLight">{loading?<tr><td colSpan="6" className="py-14 text-center text-xs font-bold text-textMuted">Loading outbound queue...</td></tr>:filtered.map(r=><tr key={r.so} className="hover:bg-indigo-50/30"><td className="px-6 py-4 font-black text-primary"><FileText size={15} className="inline mr-2"/>{r.so}</td><td className="px-6 py-4 font-bold">{r.artikel}</td><td className="px-6 py-4"><span className="inline-flex items-center gap-1.5 text-xs font-bold"><Globe size={13} className="text-primary"/>{String(r.destination||'-').toUpperCase()}</span></td><td className="px-6 py-4 text-center font-black">{r.total_cartons}</td><td className="px-6 py-4 text-center font-black">{Number(r.total_pcs).toLocaleString()}</td><td className="px-6 py-4 text-right"><button disabled={busy===r.so} onClick={()=>execute(r.so)} className="btn-primary py-2.5 px-4 text-xs inline-flex items-center gap-2 disabled:opacity-50"><Send size={13}/>{busy===r.so?'Processing...':'Ship to Buyer'}</button></td></tr>)}{!loading&&!filtered.length&&<tr><td colSpan="6" className="py-14 text-center text-xs font-bold text-textMuted">No active shipments.</td></tr>}</tbody></table></div></div></div>
}
