import { useEffect, useMemo, useState } from 'react';
import { FileSpreadsheet, RefreshCw, Search } from 'lucide-react';
import { api } from '../services/api';

export default function SoList() {
  const [rows, setRows] = useState([]); const [term, setTerm] = useState(''); const [loading, setLoading] = useState(true);
  const load = async () => { try { setLoading(true); const r = await api.so.list(); setRows(r.data || []); } catch (e) { alert(e.message); } finally { setLoading(false); } };
  useEffect(() => { load(); }, []);
  const filtered = useMemo(() => { const q=term.toUpperCase().trim(); return rows.filter(r => !q || [r.so_number,r.artikel,r.destination,r.lokasi].some(v=>String(v||'').toUpperCase().includes(q))); }, [rows,term]);
  return <div className="max-w-7xl mx-auto space-y-5">
    <div className="flex flex-col md:flex-row md:items-center md:justify-between gap-4"><div><h2 className="text-xl font-black">SO Master List</h2><p className="text-xs font-semibold text-textMuted mt-1">Aggregated directly by the backend from active inbound cartons.</p></div><div className="flex gap-2"><div className="relative w-full md:w-80"><Search size={15} className="absolute left-3.5 top-3 text-textMuted"/><input className="form-input pl-10 uppercase" placeholder="Search SO, Article, Destination..." value={term} onChange={e=>setTerm(e.target.value)}/></div><button onClick={load} className="px-3 rounded-xl border border-borderLight bg-surface text-textMuted hover:text-primary"><RefreshCw size={16} className={loading?'animate-spin':''}/></button></div></div>
    <div className="bg-surface border border-borderLight rounded-2xl shadow-sm overflow-hidden"><div className="overflow-x-auto"><table className="w-full min-w-[900px]"><thead><tr className="bg-bgBody border-b border-borderLight text-[10px] uppercase tracking-wider text-textMuted"><th className="px-6 py-4 text-left">SO Number</th><th className="px-6 py-4 text-left">Article</th><th className="px-6 py-4 text-left">Destination</th><th className="px-6 py-4 text-left">Location</th><th className="px-6 py-4 text-center">Cartons</th><th className="px-6 py-4 text-center">Qty</th><th className="px-6 py-4 text-left">Sizes</th></tr></thead><tbody className="divide-y divide-borderLight">{loading?<tr><td colSpan="7" className="py-14 text-center text-xs font-bold text-textMuted">Loading SO master...</td></tr>:filtered.map(r=><tr key={r.so_number} className="hover:bg-indigo-50/30"><td className="px-6 py-4 font-black text-primary"><FileSpreadsheet size={15} className="inline mr-2"/>{r.so_number}</td><td className="px-6 py-4 font-bold">{r.artikel}</td><td className="px-6 py-4 text-xs font-semibold">{r.destination}</td><td className="px-6 py-4 text-emerald-700 font-semibold">{r.lokasi}</td><td className="px-6 py-4 text-center font-black">{Number(r.total_cartons||0).toLocaleString()}</td><td className="px-6 py-4 text-center font-black">{Number(r.total_pcs||0).toLocaleString()}</td><td className="px-6 py-4 text-xs font-bold text-textMuted">{r.sizes?.join(', ') || '-'}</td></tr>)}{!loading&&!filtered.length&&<tr><td colSpan="7" className="py-14 text-center text-xs font-bold text-textMuted">No SO records found.</td></tr>}</tbody></table></div></div>
  </div>;
}
